---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-oauth2-proxy.fullname" . }}
  labels:
    {{- include "azure-oauth2-proxy.labels" . | nindent 4 }}
data:
  OAUTH2_PROXY_COOKIE_SECRET: {{ template "azure-oauth2-proxy.cookieSecret" . }}
  {{- if not .Values.oauth2Config.existingSecret }}
  {{- with .Values.oauth2Config }}
  OAUTH2_PROXY_AZURE_TENANT: {{ .azureTenantID | b64enc | quote}}
  OAUTH2_PROXY_CLIENT_ID: {{ .clientID | b64enc | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
