apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-oauth2-proxy.fullname" . }}
  labels:
    {{- include "azure-oauth2-proxy.labels" . | nindent 4 }}
spec:
  ports:
    - port: 4180
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "azure-oauth2-proxy.selectorLabels" . | nindent 4 }}
